# Generated by Django 5.1.4 on 2025-01-12 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('verifier', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='recruiter',
            managers=[
            ],
        ),
        migrations.AlterField(
            model_name='recruiter',
            name='password',
            field=models.CharField(max_length=128, verbose_name='password'),
        ),
    ]
