# Generated by Django 5.1.7 on 2025-03-23 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('verifier', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='chat',
            old_name='message',
            new_name='content',
        ),
        migrations.AddField(
            model_name='chat',
            name='job_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
