# Generated by Django 5.1.4 on 2025-01-12 07:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('verifier', '0002_alter_recruiter_managers_alter_recruiter_password'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recruiter',
            name='groups',
        ),
        migrations.RemoveField(
            model_name='recruiter',
            name='user_permissions',
        ),
    ]
