# Generated by Django 5.1.4 on 2025-03-23 08:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('verifier', '0002_rename_message_chat_content_chat_job_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chat',
            name='job_id',
        ),
    ]
