# Generated by Django 5.1.4 on 2025-01-12 07:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('verifier', '0003_remove_recruiter_groups_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='job',
            name='required_experience',
        ),
    ]
