# Generated by Django 5.1.4 on 2025-01-12 10:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('verifier', '0004_remove_job_required_experience'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shortlist',
            name='job_id',
            field=models.ForeignKey(db_column='job_id', on_delete=django.db.models.deletion.CASCADE, to='verifier.job'),
        ),
        migrations.AlterField(
            model_name='shortlist',
            name='resume_id',
            field=models.ForeignKey(db_column='resume_id', on_delete=django.db.models.deletion.CASCADE, to='verifier.resume'),
        ),
        migrations.AlterField(
            model_name='shortlist',
            name='shortlisted_by',
            field=models.ForeignKey(db_column='shortlisted_by', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterModelTable(
            name='shortlist',
            table='shortlist',
        ),
    ]
